# Generated by Django 4.2 on 2023-04-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_category_alter_article_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقاله ها'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'تماس', 'verbose_name_plural': 'تماس ها'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'نمونه کار', 'verbose_name_plural': 'نمونه کارها'},
        ),
    ]
